version: '3.3'

services:
  node:
    container_name: ${APPNAME}
    build: .
    volumes:
      - ./data:/srv/app/data
    labels:
      # HTTP
      - "traefik.http.routers.${APPNAME}.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.${APPNAME}.entrypoints=80"
    networks:
      - traefik
networks:
  traefik:
    external:
      name: traefik_web