version: '3.3'

services:
  node:
    container_name: colourchallenge
    build: .
    volumes:
      - ./data:/srv/app/data
    labels:
      domain: colourchallenge.studiole.uk
    restart: unless-stopped
    networks:
      - traefik
networks:
  traefik:
    external:
      name: traefik_web